import { setupAuthServices } from "./setup/authSetup"
import { setupMiddlewareServices } from "./setup/middlewareSetup"
import { setupUserServices } from "./setup/userSetup"

const SERVICES = {
  // Auth Middleware
  AUTH_MIDDLEWARE_COMMON: Symbol('AUTH_MIDDLEWARE_COMMON'),
  AUTH_MIDDLEWARE_VALIDATE: Symbol('AUTH_MIDDLEWARE_VALIDATE'),
  AUTH_MIDDLEWARE_REPOSITORY: Symbol('AUTH_MIDDLEWARE_REPOSITORY'),
  AUTH_MIDDLEWARE_USECASE: Symbol('AUTH_MIDDLEWARE_USECASE'),
  AUTH_MIDDLEWARE_CONTROLLER: Symbol('AUTH_MIDDLEWARE_CONTROLLER'),

  // Login
  LOGIN_COMMON: Symbol('LOGIN_COMMON'),
  LOGIN_VALIDATE: Symbol('LOGIN_VALIDATE'),
  LOGIN_REPOSITORY: Symbol('LOGIN_REPOSITORY'),
  LOGIN_USECASE: Symbol('LOGIN_USECASE'),
  LOGIN_CONTROLLER: Symbol('LOGIN_CONTROLLER'),

  // Create User
  CREATE_USER_COMMON: Symbol('CREATE_USER_COMMON'),
  CREATE_USER_VALIDATE: Symbol('CREATE_USER_VALIDATE'),
  CREATE_USER_REPOSITORY: Symbol('CREATE_USER_REPOSITORY'),
  CREATE_USER_USECASE: Symbol('CREATE_USER_USECASE'),
  CREATE_USER_CONTROLLER: Symbol('CREATE_USER_CONTROLLER'),

  // Get User By ID
  GET_USER_COMMON: Symbol('GET_USER_COMMON'),
  GET_USER_VALIDATE: Symbol('GET_USER_VALIDATE'),
  GET_USER_REPOSITORY: Symbol('GET_USER_REPOSITORY'),
  GET_USER_USECASE: Symbol('GET_USER_USECASE'),
  GET_USER_CONTROLLER: Symbol('GET_USER_CONTROLLER'),

  // Logout
  LOGOUT_COMMON: Symbol('LOGOUT_COMMON'),
  LOGOUT_VALIDATE: Symbol('LOGOUT_VALIDATE'),
  LOGOUT_REPOSITORY: Symbol('LOGOUT_REPOSITORY'),
  LOGOUT_USECASE: Symbol('LOGOUT_USECASE'),
  LOGOUT_CONTROLLER: Symbol('LOGOUT_CONTROLLER'),

  // Role Middleware
  ROLE_MIDDLEWARE_COMMON: Symbol('ROLE_MIDDLEWARE_COMMON'),
  ROLE_MIDDLEWARE_VALIDATE: Symbol('ROLE_MIDDLEWARE_VALIDATE'),
  ROLE_MIDDLEWARE_USECASE: Symbol('ROLE_MIDDLEWARE_USECASE'),
  ROLE_MIDDLEWARE_CONTROLLER: Symbol('ROLE_MIDDLEWARE_CONTROLLER'),

  // Ownership Middleware
  OWNERSHIP_MIDDLEWARE_USECASE: Symbol('OWNERSHIP_MIDDLEWARE_USECASE'),
  OWNERSHIP_MIDDLEWARE_CONTROLLER: Symbol('OWNERSHIP_MIDDLEWARE_CONTROLLER'),
}


function setupDIContainer(): void {
  setupAuthServices()
  setupUserServices()
  setupMiddlewareServices()

  console.log('[DIContainer] inicializado com sucesso!')
}

export { setupDIContainer, SERVICES }
